version: '3'
services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    ports:
      - 3000:1234
    tty:
      true
    volumes:
      - ./src/app:/go/src/app

